import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import ta

# Ticker listeleri (tam listeyi buraya yapıştırabilirsin)
tickers_nyse = """A-AA-AAP-ABBV-ABR-ABT-ACHR-ACI-ACM-ACN-ACVA-ADC-ADM-ADNT-ADT-AEE-AEG-AEM-AEO-AER-AES-AESI-AFL-AG-AGI-AGL-AHR-AI-AIG-AJG-AKR-ALB-ALC-ALK-ALL-ALLY-AM-AMCR-AME-AMH-AMPS-AMT-AMTM-AMX-ANET-ANF-AON-AOS-APD-APG-APH-APLE-APO-APTV-AQN-AR-ARCO-ARE-ARES-ARI-ARMK-AROC-ARR-AS-ASAN-ASB-ASPN-ASX-ATEN-ATI-AU-AUB-AVTR-AWK-AXP-AXTA-AZEK-BA-BABA-BAC-BAH-BALL-BAM-BANC-BAX-BBVA-BBWI-BBY-BCE-BCS-BDX-BE-BEKE-BEN-BEPC-BERY-BF.B-BG-BGS-BHP-BHVN-BILL-BIRK-BJ-BK-BKD-BLDR-BMY-BN-BNL-BNS-BOX-BP-BRBR-BRK.B-BRO-BROS-BRX-BSX-BTI-BTU-BUD-BURL-BVN-BWA-BX-BXMT-BXP-BXSL-C-CADE-CAG-CAH-CARR-CAT-CAVA-CB-CBRE-CC-CCI-CCJ-CCK-CCL-CDE-CDP-CE-CF-CFG-CHD-CHWY-CI-CIEN-CIVI-CL-CLF-CLS-CLX-CM-CMA-CMC-CMG-CMS-CNC-CNH-CNI-CNK-CNM-CNP-CNQ-CNX-COF-COHR-COLD-COMP-COP-COR-COTY-COUR-CP-CPNG-CPRI-CRBG-CRGY-CRH-CRI-CRK-CRL-CRM-CSTM-CTRA-CTRE-CTVA-CUBE-CUK-CUZ-CVE-CVI-CVNA-CVS-CVX-CWAN-CWH-CWK-CX-CXM-CXW-D-DAL-DAN-DAR-DAY-DB-DBRG-DD-DE-DEA-DECK-DEI-DELL-DEO-DESP-DFS-DG-DGX-DHI-DHR-DHT-DINO-DIS-DK-DKS-DLR-DNA-DNB-DNOW-DOC-DOCN-DOCS-DOW-DRH-DRI-DT-DTE-DTM-DUK-DV-DVN-DX-DXC-EAT-EBR-EC-ECC-ECL-ED-EDU-EFC-EFX-EGO-EIX-EL-ELAN-ELF-ELS-ELV-EMN-EMR-ENB-ENFN-EOG-EPD-EPRT-EQH-EQNR-EQR-EQT-ERJ-ES-ESI-ESRT-ESTC-ET-ETN-ETR-EVH-EW-EXPD-EXR-F-FBIN-FBP-FCX-FDX-FE-FERG-FHN-FI-FIS-FL-FLG-FLO-FLR-FLS-FLUT-FMC-FNA-FNB-FND-FNF-FOUR-FR-FRO-FSK-FSLY-FSM-FTI-FTV-FUN-G-GAP-GD-GDDY-GE-GENI-GEO-GES-GEV-GFI-GFL-GIS-GLW-GM-GME-GMED-GNL-GNW-GOF-GOLD-GPC-GPK-GPN-GRND-GS-GSK-GTES-GXO-HAL-HASI-HAYW-HBM-HCA-HD-HDB-HE-HES-HESM-HIG-HIMS-HIW-HL-HLF-HLN-HLT-HLX-HMC-HMY-HOG-HOMB-HP-HPE-HPQ-HR-HRB-HRL-HSBC-HSY-HTGC-HUM-HUN-HWM-HXL-IAG-IBM-IBN-ICE-IFF-IGT-INFA-INFY-ING-INVH-IONQ-IOT-IP-IPG-IQV-IRDM-IREN-ISRG-JD-KC-KDP-KHC-KLAC-KROS-KTOS-KURA-LBTYA-LBTYK-LEGN-LFST-LI-LIN-LINE-LITE-LKQ-LNT-LRCX-LSCC-LULU-LUNR-LX-LYFT-LZ-MAR-MARA-MAT-MBLY-MCHP-MCW-MDB-MDLZ-META-MGNI-MKSI-MNMD-MNST-MOMO-MRNA-MRVL-MSFT-MSTR-MTCH-MU-MXL-NAMS-NBIS-NBIX-NCNO-NDAQ-NEO-NEOG-NEXT-NFE-NFLX-NMRK-NN-NNE-NTAP-NTES-NTLA-NTNX-NTRA-NTRS-NVAX-NVDA-NWSA-NXPI-NXT-OCUL-ODFL-OKTA-OLLI-ON-ONB-OPCH-OS-OTEX-OUST-OZK-PAA-PAGP-PANW-PARA-PAYO-PAYX-PCAR-PCT-PCVX-PDCO-PDD-PENN-PEP-PFG-PGNY-PGY-PINC-PLAY-PLTR-PLYA-PONY-PPC-PRCH-PTC-PTEN-PTLO-PTON-PYPL-PZZA-QCOM-QFIN-QRVO-QUBT-QURE-RCAT-RCKT-RDFN-REG-RELY-RGTI-RIOT-RIVN-RKLB-RNA-ROIV-ROKU-ROST-RPRX-RUM-RUN-RVMD-RXRX-RYAAY-SAGE-SATS-SBLK-SBRA-SBUX-SEDG-SERV-SFM-SGRY-SHC-SHOO-SHOP-SIRI-SLM-SMCI-SMMT-SMPL-SMTC-SNDX-SNPS-SNY-SOFI-SONO-SOUN-SPRY-SRAD-SRPT-SRRK-SSNC-SSRM-STLD-STNE-STX-SWKS-SWTX-SYM-TCOM-TEAM-TECH-TEM-TENB-TER-TGTX-TIGR-TLN-TMDX-TMUS-TNDM-TPG-TRIP-TRMB-TRMD-TROW-TRVI-TSCO-TSLA-TTD-TTEK-TTWO-TVTX-TW-TWST-TXG-TXN-TXRH-UAL-UDMY-ULTA-UPST-UPWK-URBN-VERX-VIAV-VIR-VITL-VKTX-VLY-VNET-VNOM-VOD-VRNA-VRNS-VRRM-VRTX-VSAT-VTRS-WAY-WB-WBA-WBD-WDAY-WDC-WEN-WFRD-WMG-WRD-WSC-WVE-WYNN-XEL-XP-XRAY-Z-ZI-ZION-ZM-ZS""".strip().split("-")
tickers_nasdaq = """AAL-AAOI-AAPL-ABNB-ACAD-ACGL-ACHC-ACMR-ADBE-ADI-ADMA-ADP-ADPT-ADSK-ADTN-AEP-AFRM-AGNC-AHCO-AKAM-AKRO-ALAB-ALGM-ALHC-ALKS-ALKT-AMAT-AMD-AMGN-AMKR-AMRX-AMZN-APA-APLD-APLS-APP-ARCC-ARHS-ARM-ARQT-ARVN-ARWR-ASML-ASO-ASPI-ASTS-ATAT-ATEC-ATSG-AUPH-AVDL-AVDX-AVGO-AVPT-AVXL-AZN-BBIO-BCRX-BEAM-BECN-BGC-BIDU-BIIB-BILI-BKR-BLMN-BMRN-BRKR-BRZE-BSY-BTDR-BTSG-BZ-CAKE-CAPR-CAR-CARG-CART-CCCS-CCEP-CDNS-CDW-CEG-CELH-CENX-CERT-CFLT-CG-CGNX-CHRW-CHTR-CHX-CLBT-CLMT-CLSK-CMCSA-CME-CMRX-COIN-COLB-COO-CORT-CORZ-COST-CPB-CPRT-CPRX-CRDO-CRMD-CRNC-CROX-CRSP-CRWD-CSCO-CSGP-CSIQ-CSX-CTAS-CTSH-CYTK-CZR-DASH-DAWN-DBX-DDOG-DJT-DKNG-DLTR-DNLI-DOCU-DVAX-DXCM-DYN-EA-EBAY-EBC-EH-ENPH-ENTG-ENVX-ERIC-ETNB-ETSY-EVRG-EWBC-EWTX-EXAS-EXC-EXE-EXEL-EXLS-EXPE-EXPI-EXTR-EYE-FA-FANG-FAST-FITB-FIVE-FIVN-FLEX-FLYW-FOLD-FOX-FOXA-FRPT-FRSH-FSLR-FTAI-FTNT-FTRE-FULT-FUTU-FWONK-FYBR-GBDC-GCT-GDS-GEHC-GEN-GFS-GGAL-GH-GILD-GLBE-GLNG-GLPI-GMAB-GNTX-GO-GOGL-GOGO-GOOG-GOOGL-GRAL-GRFS-GRPN-GRRR-GT-GTLB-GTX-HALO-HAS-HBAN-HIMX-HLIT-HLMN-HOLX-HON-HOOD-HSAI-HSIC-HST-HTHT-HUT-IAC-IBKR-ICLR-IDYA-ILMN-IMNM-IMVT-INCY-INDV-INMD-INOD-INSM-INTC-INTR-INTU-IONS-IRDM-IREN-ISRG-JD-KC-KDP-KHC-KLAC-KROS-KTOS-KURA-LBTYA-LBTYK-LEGN-LFST-LI-LIN-LINE-LITE-LKQ-LNT-LRCX-LSCC-LULU-LUNR-LX-LYFT-LZ-MAR-MARA-MAT-MBLY-MCHP-MCW-MDB-MDLZ-META-MGNI-MKSI-MNMD-MNST-MOMO-MRNA-MRVL-MSFT-MSTR-MTCH-MU-MXL-NAMS-NBIS-NBIX-NCNO-NDAQ-NEO-NEOG-NEXT-NFE-NFLX-NMRK-NN-NNE-NTAP-NTES-NTLA-NTNX-NTRA-NTRS-NVAX-NVDA-NWSA-NXPI-NXT-OCUL-ODFL-OKTA-OLLI-ON-ONB-OPCH-OS-OTEX-OUST-OZK-PAA-PAGP-PANW-PARA-PAYO-PAYX-PCAR-PCT-PCVX-PDCO-PDD-PENN-PEP-PFG-PGNY-PGY-PINC-PLAY-PLTR-PLYA-PONY-PPC-PRCH-PTC-PTEN-PTLO-PTON-PYPL-PZZA-QCOM-QFIN-QRVO-QUBT-QURE-RCAT-RCKT-RDFN-REG-RELY-RGTI-RIOT-RIVN-RKLB-RNA-ROIV-ROKU-ROST-RPRX-RUM-RUN-RVMD-RXRX-RYAAY-SAGE-SATS-SBLK-SBRA-SBUX-SEDG-SERV-SFM-SGRY-SHC-SHOO-SHOP-SIRI-SLM-SMCI-SMMT-SMPL-SMTC-SNDX-SNPS-SNY-SOFI-SONO-SOUN-SPRY-SRAD-SRPT-SRRK-SSNC-SSRM-STLD-STNE-STX-SWKS-SWTX-SYM-TCOM-TEAM-TECH-TEM-TENB-TER-TGTX-TIGR-TLN-TMDX-TMUS-TNDM-TPG-TRIP-TRMB-TRMD-TROW-TRVI-TSCO-TSLA-TTD-TTEK-TTWO-TVTX-TW-TWST-TXG-TXN-TXRH-UAL-UDMY-ULTA-UPST-UPWK-URBN-VERX-VIAV-VIR-VITL-VKTX-VLY-VNET-VNOM-VOD-VRNA-VRNS-VRRM-VRTX-VSAT-VTRS-WAY-WB-WBA-WBD-WDAY-WDC-WEN-WFRD-WMG-WRD-WSC-WVE-WYNN-XEL-XP-XRAY-Z-ZI-ZION-ZM-ZS""".strip().split("-")

# LRC hesaplama
def linear_regression_channel(df, length=100):
    if len(df) < length:
        return None, None
    y = df['Close'][-length:].values
    x = np.arange(length)
    coeffs = np.polyfit(x, y, 1)
    y_fit = coeffs[0] * x + coeffs[1]
    resid = y - y_fit
    std_dev = np.std(resid)
    return y_fit[-1] + std_dev, y_fit[-1] - std_dev

# LRC sinyali kontrol
def check_lrc_cross(df, length, lookback):
    if len(df) < length + lookback:
        return None
    for i in range(lookback):
        sub_df = df.iloc[-(length + i):-i or None]
        upper, lower = linear_regression_channel(sub_df, length)
        if upper is None or lower is None:
            continue
        close = sub_df['Close'].iloc[-1]
        prev = sub_df['Close'].iloc[-2]
        if prev < upper and close > upper:
            return "LRC Cross Over"
        if prev > lower and close < lower:
            return "LRC Cross Under"
    return None

# SAR sinyali kontrol
def check_single_sar(df):
    if len(df) < 3:
        return None
    sar = ta.trend.PSARIndicator(df['High'], df['Low'], df['Close']).psar()
    current = sar.iloc[-1]
    prev = sar.iloc[-2]
    prev_prev = sar.iloc[-3]
    change_up = prev_prev < df['Close'].iloc[-3] and prev > df['Close'].iloc[-2]
    change_down = prev_prev > df['Close'].iloc[-3] and prev < df['Close'].iloc[-2]
    if change_up or change_down:
        return "Tek SAR"
    return None

# Streamlit UI
st.title("📈 NYSE / NASDAQ Teknik Taraması")

exchange = st.radio("Borsa", ["NASDAQ", "NYSE"])
interval = st.selectbox("Zaman Dilimi", ["1wk", "3d", "1d", "4h"])
lookback = st.slider("Kaç bar içinde sinyal aransın?", 1, 50, 20)
scan_lrc = st.checkbox("LRC Kesişme Tara")
scan_sar = st.checkbox("Tek SAR Tara")

if st.button("Taramayı Başlat"):
    tickers = tickers_nasdaq if exchange == "NASDAQ" else tickers_nyse
    st.info(f"{len(tickers)} hisse taranıyor...")
    results = []

    for ticker in tickers:
        try:
            df = yf.download(ticker, period="500d", interval=interval, progress=False)
            if df.empty:
                continue
            if scan_lrc:
                signal = check_lrc_cross(df, length=100, lookback=lookback)
                if signal:
                    results.append({"Ticker": ticker, "Sinyal": signal, "Zaman": interval})
            if scan_sar:
                signal = check_single_sar(df)
                if signal:
                    results.append({"Ticker": ticker, "Sinyal": signal, "Zaman": interval})
        except Exception as e:
            continue

    if results:
        st.success(f"{len(results)} sinyal bulundu.")
        st.dataframe(pd.DataFrame(results))
    else:
        st.warning("Hiç sinyal bulunamadı.")
